version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pg_taskhub
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskhub_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_taskhub
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - taskhub_network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend_taskhub
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/taskhub_db
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskhub_db
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taskhub_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "node scripts/setupDatabaseOnce.js && echo 'ðŸš€ Iniciando servidor en puerto 4000...' && node app.js"

volumes:
  pgdata:

networks:
  taskhub_network:
    driver: bridge
